-- AlterTable
ALTER TABLE "ImportSession" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Source" ALTER COLUMN "uploadedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "uploadedAt" SET DATA TYPE TIMESTAMPTZ;
